# Generated by Django 2.2 on 2019-04-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.IntegerField()),
                ('disorder', models.CharField(max_length=100)),
                ('diagnostic', models.CharField(max_length=100)),
                ('proce', models.CharField(max_length=100)),
            ],
        ),
    ]
